### ISSUE TITLE
event listener not disabled correctly

### ISSUE THREAD

**Issue by MTG2000** [g787543/infinite-react-carousel#2]
**Describe the bug**
I have a multi-page React app where on the main page I am using a simple Slider and I am using 
react-router-dom to traverse between the pages 
so the problem is that when I go to any other page after being at the page that has the slider 
and resizing the screen I get this error :
slider.js:490   : 
 Uncaught TypeError: Cannot read property 'querySelector' of null
    at Slider.connectObserver (slider.js:490)
    at Slider.handleResize

**To Reproduce**
open a page that has a slider
unmount it ( by going to another page for example )
go back to the original page and resize the screen 

NOTE that I am using react-router-dom , if you were to not use it no problem will happen but 
if I dont use it then its not a SPA 

**Expected behavior**
the event listener will be removed or at least not fired if the slider has been unmounted

**Screenshots**

![Capture](https://user-images.githubusercontent.com/50504183/70441845-cf665800-1a9d-11ea-8499-08246696e535.PNG)

and this is the line generating the error:
![image](https://user-images.githubusercontent.com/50504183/70441949-00df2380-1a9e-11ea-80f6-044625796b32.png)

Thank you in advance

**Comment by g787543** [comment]
Hi, @MTG2000 

Thank you for your reply.
Could you give me some of your code to help me understand your problem quickly?
Or you can fork this [codesandbox](https://codesandbox.io/s/infinite-react-carousel-hwghe) and reimplement the error.

Thank you.

**Comment by MTG2000** [comment]
Thank you for the quick reply....
Here is the repository for the project

[https://github.com/MTG2000/steam-store](url)

it is a small project for training 
The slider file is in  'client/src/MainPage/GamesCarousel.jsx'

in the sandbox you provided if you open the carousel page then go back to the index you will get a similar error when resizing the page:
![image](https://user-images.githubusercontent.com/50504183/70456156-44458c00-1ab6-11ea-9bf3-63b40a69a515.png)
not sure if its something diffrent but it seems similar to a certain level

**Comment by g787543** [comment]
Hi @MTG2000 ,

Gotcha, I will look for the problem,please give me more time.

**Comment by g787543** [comment]
I already pushed the new version on npm, please try again, thanks.

**Comment by MTG2000** [comment]
I installed the new version on both the sandbox and my project
the problem seems to be fixed in the sandbox but unfortunately it still exists in my 
project :( 

![image](https://user-images.githubusercontent.com/50504183/70544032-10c93700-1b74-11ea-9660-1b21c7d7e4fa.png)


I am not sure if the problem is someplace in my code (although in the slider component I dont have any state or async calls ) or is it from the package

**Comment by g787543** [comment]
But I run your project without any errors like [video](https://drive.google.com/open?id=1GPxNy1m00x6DrlCwGW24cXs0gxCP4a3e).

Have you re-run your client scripts after update package?

**Comment by MTG2000** [comment]
Oh MY GOD !!! I Forgot to stop the client scripts and re-run them .............. (what a silly mistake)
It is now fixed :)

Thank you very much for your amazing and quick work
